# Generated by Django 4.2.13 on 2026-03-30 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[("audio", "음성(회의) 분석"), ("video", "영상(CCTV) 분석")],
                        max_length=10,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("uploaded_file", models.FileField(upload_to="uploads/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기 중"),
                            ("processing", "처리 중"),
                            ("done", "완료"),
                            ("error", "오류"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transcript",
                    models.TextField(blank=True, null=True, verbose_name="STT 전문"),
                ),
                (
                    "summary_lines",
                    models.JSONField(blank=True, null=True, verbose_name="핵심 요약 3줄"),
                ),
                (
                    "video_stats",
                    models.JSONField(blank=True, null=True, verbose_name="경영 지표"),
                ),
                (
                    "safety_events",
                    models.JSONField(blank=True, null=True, verbose_name="안전 경고 이벤트"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "분석 기록",
                "verbose_name_plural": "분석 기록 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
